# Generated by Django 5.0.6 on 2024-07-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField()),
                ('arquivo', models.FileField(upload_to='core/static/ebook', verbose_name='Arquivo')),
                ('imagem', models.ImageField(upload_to='core/static/img/ebook', verbose_name='Imagem')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ebook',
                'verbose_name_plural': 'Ebooks',
                'db_table': 'ebook',
            },
        ),
        migrations.CreateModel(
            name='NossosEbooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField()),
            ],
        ),
    ]
