# Generated by Django 5.0.6 on 2024-07-11 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.ebook', verbose_name='Ebook')),
            ],
            options={
                'verbose_name': 'Cadastro Ebook',
                'verbose_name_plural': 'Cadastro Ebooks',
                'db_table': 'cadastro_ebook',
            },
        ),
    ]
