# Generated by Django 5.0.6 on 2024-07-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NossosServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Nosso Serviço',
                'db_table': 'nossos_servicos',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='core/static/img/servico', verbose_name='Imagem')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'db_table': 'servico',
            },
        ),
    ]
