# Generated by Django 5.0.6 on 2024-07-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='core/static/img/intro', verbose_name='Foto de Exibição')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
            ],
            options={
                'verbose_name': 'Introdução',
                'verbose_name_plural': 'Introdução',
                'db_table': 'intro',
            },
        ),
    ]
