# Generated by Django 5.0.6 on 2024-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0002_nossosvalores_valores'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemQuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='core/static/img/quem_somos', verbose_name='Foto de Exibição')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
            ],
            options={
                'verbose_name': 'Imagem Quem Somos',
                'verbose_name_plural': 'Imagens Quem Somos',
                'db_table': 'imagem_quem_somos',
            },
        ),
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Quem Somos',
                'verbose_name_plural': 'Quem Somos',
                'db_table': 'quem_somos',
            },
        ),
    ]
