# Generated by Django 5.0.6 on 2024-07-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('mensagem', models.TextField(max_length=255, verbose_name='Mensagem')),
            ],
            options={
                'verbose_name': 'Contato',
                'db_table': 'contato',
            },
        ),
    ]
