# Generated by Django 5.0.6 on 2024-07-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_alter_contatoformulario_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('link_maps', models.TextField(verbose_name='Link do Google Maps')),
            ],
            options={
                'verbose_name': 'Nosso contato',
                'db_table': 'nosso_contato',
            },
        ),
    ]
