# Generated by Django 5.0.6 on 2024-07-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0003_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='contatoformulario',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Telefone'),
        ),
    ]
