# Generated by Django 5.0.6 on 2024-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='core/static/img/galeria', verbose_name='Imagem')),
                ('alt', models.CharField(max_length=100, verbose_name='Texto Alternativo')),
                ('data', models.DateField(auto_now=True, verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Galeria',
                'db_table': 'galeria',
            },
        ),
    ]
