# Generated by Django 5.0.6 on 2024-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de publicação'),
        ),
    ]
